# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
sudo: required
warnings_are_errors: false

repos:
  CRAN: http://cran.rstudio.com
  GRAN: http://owi.usgs.gov/R

before_install:
  - wget http://owi.usgs.gov/R/r-buildtools/JAGS-3.4.0.tar.gz
  - tar xfvs JAGS-3.4.0.tar.gz
  - cd JAGS-3.4.0
  - sudo ./configure
  - sudo make
  - sudo make install
  - cd ..
  - sudo rm -f JAGS-3.4.0.tar.gz
  - sudo rm -rf JAGS-3.4.0
  
r_github_packages:
  - jimhester/covr
  - appling/unitted
  - USGS-R/streamMetabolizer
  - USGS-R/sbtools
  - USGS-R/gsplot
  - USGS-R/geoknife
  - USGS-R/mda.streams

after_success:
  - Rscript -e 'covr::coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change